"""Optional policy-observation extensions for shape-aware obstacle tasks."""

from __future__ import annotations

from typing import Any

import numpy as np

from .pursuit_env import CaptureRadiusPursuit3DEnv, TETRAHEDRON_DIRECTIONS


SHAPE_AWARE_OBSTACLE_GEOMETRY = "shape_extents_and_type"


def policy_observations(
    env: CaptureRadiusPursuit3DEnv,
    observation: dict[str, Any] | None = None,
    *,
    route_helper: Any | None = None,
) -> np.ndarray:
    """Return policy features plus explicitly enabled development extensions.

    The legacy encoder remains unchanged so historical checkpoints retain their
    input contract. V4 appends horizontal half-extents and a one-hot
    cylinder/box/wall type to every obstacle description. A development-only
    role/slot block can be enabled independently; it is deliberately disabled
    by default and must not be enabled in the frozen Phase86 comparison. A
    route-intent block is also opt-in and must be generated by a persistent
    public-belief route helper owned by the caller. Keeping the helper outside
    this pure encoder is important because route planning has temporal state;
    constructing it inside this function would silently reset the route every
    environment step.
    """
    current = env.observe() if observation is None else observation
    base = env.policy_observations(current)
    mode = str(env.task.get("policy_obstacle_geometry", "legacy"))
    if mode == "legacy":
        values = base
    elif mode == SHAPE_AWARE_OBSTACLE_GEOMETRY:
        positions = np.asarray(current["defender_positions"], dtype=np.float32)
        obstacles = list(current["obstacles"])
        extent = float(env.world["half_extent_xy"])
        max_obstacles = int(env.pursuit["max_observation_obstacles"])
        geometry_rows: list[np.ndarray] = []
        for position in positions:
            nearest = sorted(
                obstacles,
                key=lambda obstacle: float(
                    np.linalg.norm(np.asarray(obstacle["center_xy"], dtype=np.float32) - position[:2])
                    - float(obstacle["radius"])
                ),
            )[:max_obstacles]
            geometry = np.zeros((max_obstacles, 5), dtype=np.float32)
            for index, obstacle in enumerate(nearest):
                shape = str(obstacle["shape"])
                if shape not in {"cylinder", "box", "wall"}:
                    raise ValueError(f"Unsupported obstacle shape in policy observation: {shape}")
                half_extents = obstacle.get("half_extents_xy")
                if half_extents is None:
                    half_x = half_y = float(obstacle["radius"])
                else:
                    half_x, half_y = map(float, half_extents)
                geometry[index] = np.array(
                    [
                        half_x / extent,
                        half_y / extent,
                        float(shape == "cylinder"),
                        float(shape == "box"),
                        float(shape == "wall"),
                    ],
                    dtype=np.float32,
                )
            geometry_rows.append(geometry.reshape(-1))
        values = np.concatenate([base, np.stack(geometry_rows)], axis=1).astype(np.float32)
    else:
        raise ValueError(
            "task.policy_obstacle_geometry must be 'legacy' or "
            f"'{SHAPE_AWARE_OBSTACLE_GEOMETRY}'."
        )

    if bool(env.task.get("policy_role_slot_features", False)):
        radius = float(env.task.get("policy_role_slot_radius_m", 1.25))
        if radius <= 0.0:
            raise ValueError("task.policy_role_slot_radius_m must be positive.")
        if env.n_defenders != len(TETRAHEDRON_DIRECTIONS):
            raise ValueError("Fixed role/slot features require four defenders.")
        positions = np.asarray(current["defender_positions"], dtype=np.float32)
        beliefs = np.asarray(current["target_belief_positions"], dtype=np.float32)
        offsets = np.zeros((env.n_defenders, 3), dtype=np.float32)
        # Role 0 is the fixed interceptor. Roles 1--3 hold a tetrahedral
        # blocker formation around the current local target belief.
        offsets[1:] = (TETRAHEDRON_DIRECTIONS[1:] * radius).astype(np.float32)
        slot_delta = (beliefs + offsets - positions) / extent
        role_one_hot = np.eye(env.n_defenders, dtype=np.float32)
        values = np.concatenate([values, slot_delta, role_one_hot], axis=1)
    if bool(env.task.get("policy_route_intent_features", False)):
        if route_helper is None:
            raise ValueError(
                "task.policy_route_intent_features is enabled but no persistent "
                "public-belief route helper was provided."
            )
        route_values = np.asarray(route_helper.route_features(current), dtype=np.float32)
        expected_shape = (env.n_defenders, 7)
        if route_values.shape != expected_shape:
            raise ValueError(
                "Public-belief route helper emitted an incompatible feature shape: "
                f"expected={expected_shape}, got={route_values.shape}."
            )
        values = np.concatenate([values, route_values], axis=1)
    if not np.isfinite(values).all():
        raise RuntimeError("Shape-aware policy observation emitted a non-finite value.")
    return values
